### ISSUE TITLE
undefined reference to `vtable for dyn'

### ISSUE THREAD

**Issue by gumoraes999999** [amusecode/SeBa#22]
I was trying to compile it

**Comment by silviatoonen** [comment]
This sometimes happens if a previous compilation failes - Can you try running make clean before compiling?

**Comment by gumoraes999999** [comment]
same error.

**Comment by evertrol** [comment]
The problem is that newer compilers (for example, gcc 13; or rather, the newer C++ standard), introduce new functions. In this case, the `beta` function. If you compile the base, you'll find an error:
```
dyn_external.C:429:33: error: reference to 'beta' is ambiguous
```
which is the `dyn` from the title, that is being searched for when compiling SeBa: it simply wasn't compiled because of this error, and then not included in the static library. It's just that the Makefiles are set up such that the compliation for other files continues, and a final library is made, just without this "symbol" (function).

A workaround is to set a C++ standard. C++11 seems to be still okay; C++17 is the standard where things go wrong (I haven't checked C++14, that should also work).

This, however, doesn't fix the underlying problem: it's a nameclash between a variable called `beta` and a function called `beta` from the standard library (so actually `std::beta`).

But somewhere, in `include/stdinc.h`, there is the infamous line:
```
using namespace std;
```

which is generally strongly disadvised. Exactly because of this reason: name clashes between standard library names and local names. In this case, the `beta` in
```
void set_friction_beta(real b) {beta = b;}
```
and [`std::beta` (the beta function) introduced in C++ 17](https://en.cppreference.com/w/cpp/numeric/special_functions/beta).

One way to solve this more properly, is to replace 
```
using namespace std;
```
with
```
using std::cout;
using std::cerr;
using std::cin;
using std::endl;
using std::ostream;
using std::istream;
using std::vector;
```

in `include/stdinc.h`.

I haven't fully checked, but I think this includes all names used from the standard library in the code.

Even better would be (slightly more work, but a good `sed` command can help) to replace all occurrences of `cout`, `cerr`, `cin`, `endl`, `ostream`, `istream` and `vector` with `std::cout`, `std::cerr` etc. That makes it absolutely clear what is being meant, and avoids this problem completely. To quote the Zen of Python:
> Namespaces are one honking great idea -- let's do more of those!

As an extra: these using directives should likely not be used in an include files, since this file gets included nearly *everywhere*. Instead, each source file that uses any of these stdlib names should include them explicitly. Ditto for the stdlib include files in `stdinc.h`: these should be included in the actual source file, where needed.
Or, again with the Zen of Python(*):
> Explicit is better than implicit.

But using `std::<name>` is even better, of course.

(*) Never disregard other languages when programming!

**Comment by rieder** [comment]
@spzwart did you try building with gcc-13?
